name: Execute e2e tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    e2e:
        runs-on: ubuntu-latest
        env:
            CI: true
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - run: npm ci
            - run: npm run build
            - run: npm run test:e2e:ci
